kind: Secret
apiVersion: v1
metadata:
  name: s3-example
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-protocol: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/display-name: s3-example
data:
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_S3_BUCKET: dGVzdA==
  AWS_S3_ENDPOINT: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
type: Opaque
